---
all:
  children:
    cisco_devices:
      hosts:
        # NA Devices
        router1NA:
          ansible_host: 10.47.64.10
        router2NA:
          ansible_host: 10.47.64.11
        router4NA:
          ansible_host:10.47.64.12
        router5NA:
          ansible_host: 10.47.64.13
        L3S1NA:
          ansible_host: 10.47.64.14
        L3S2NA:
          ansible_host: 10.47.64.15
        L2S1NA:
          ansible_host: 10.47.64.16
        L2S2NA:
          ansible_host: 10.47.64.17
        L2S3NA:
          ansible_host: 10.47.64.18

        # EU Devices
        router1EU:
          ansible_host: 10.47.128.10
        router2EU:
          ansible_host: 10.47.128.11
        router4EU:
          ansible_host: 10.47.128.12
        router5EU:
          ansible_host: 10.47.128.13
        L3S1EU:
          ansible_host: 10.47.128.14
        L3S2EU:
          ansible_host: 10.47.128.15
        L2S1EU:
          ansible_host: 10.47.128.16
        L2S2EU:
          ansible_host: 10.47.128.17
        L2S3EU:
          ansible_host: 10.47.128.18

        # AS Devices
        router1AS:
          ansible_host: 10.47.192.10
        router2AS:
          ansible_host: 10.47.192.11
        router4AS:
          ansible_host: 10.47.192.12
        router5AS:
          ansible_host: 10.47.192.13
        L3S1AS:
          ansible_host: 10.47.192.14
        L3S2AS:
          ansible_host: 10.47.192.15
        L2S1AS:
          ansible_host: 10.47.192.16
        L2S2AS:
          ansible_host: 10.47.192.17
        L2S3AS:
          ansible_host: 10.47.192.18

        # ISP Devices
        L3S1ISP:
          ansible_host: 10.47.0.10
        L3S2ISP:
          ansible_host: 10.47.0.11
        L3S3ISP:
          ansible_host: 10.47.0.12
        L3S4ISP:
          ansible_host: 10.47.0.13
        
      # Group vars for all hosts in cisco_devices
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: admin
        ansible_password: admin

      # Privilege escalation
      ansible_become: true
      ansible_become_method: enable
      ansible_become_password: admin


