---
all:
  children:
    cisco_devices:
      hosts:
        # NA Devices
        router1NA:
          ansible_host: 
        router2NA:
          ansible_host:
        router4NA:
          ansible_host:
        router5NA:
          ansible_host:
        L3S1NA:
          ansible_host:
        L3S2NA:
          ansible_host:
        L2S1NA:
          ansible_host:
        L2S2NA:
          ansible_host:
        L2S3NA:
          ansible_host:

        # EU Devices
        router1EU:
          ansible_host:
        router2EU:
          ansible_host:
        router4EU:
          ansible_host:
        router5EU:
          ansible_host:
        L3S1EU:
          ansible_host:
        L3S2EU:
          ansible_host:
        L2S1EU:
          ansible_host:
        L2S2EU:
          ansible_host:
        L2S3EU:
          ansible_host:

        # AS Devices
        router1AS:
          ansible_host: 
        router2AS:
          ansible_host:
        router4AS:
          ansible_host:
        router5AS:
          ansible_host:
        L3S1AS:
          ansible_host:
        L3S2AS:
          ansible_host:
        L2S1AS:
          ansible_host:
        L2S2AS:
          ansible_host:
        L2S3AS:
          ansible_host:

        # ISP Devices
        L3S1ISP:
          ansible_host:
        L3S2ISP:
          ansible_host:
        L3S3ISP:
          ansible_host:
        L3S4ISP:
          ansible_host:
        
      # Group vars for all hosts in cisco_devices
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: admin
        ansible_password: admin

      # Privilege escalation
      ansible_become: true
      ansible_become_method: enable
      ansible_become_password: admin


