---
# PLACEHOLDER EXAMPLE FOR FUTURE USE OF PLAYBOOKS

hostname: router1NA

enable_ip_routing: true
enable_ipv6_routing: true

misc_config:
  - description: AS inbound prefix list
    lines:
      - "ip prefix-list AS_INBOUND seq 5 permit 10.47.64.0/19 le 32"
  
  - description: BGP to EIGRP route map
    parents:
      - "route-map BGP-EIGRP"
    lines:
      - "match ip address prefix-list AS_INBOUND"

  - description: BGP IPv4 address family
    parents:
      - "router bgp 65515"
      - "address-family ipv4 unicast"
    lines:
      - "network 10.47.209.1 mask 255.255.255.255"

      - network: 10.47.128.0
        wildcard: 0.0.0.255
        area: 0

interfaces:
  - name: GigabitEthernet0/0/0
    description: Link to ISPS2
    ip: 10.47.116.6
    mask: 255.255.255.252

  - name: GigabitEthernet0/0/1
    description: Link to L3S1
    ip: 10.47.80.1
    mask: 255.255.255.252
  - name: 10
    ip: 10.47.81.1
    mask: 255.255.255.255
