--- 
- name: Configure misc settings
  hosts: cisco_devices
  gather_facts: false

  tasks:
    - name: Configure hostname
      cisco.ios.ios_config:
        lines:
          - "hostname {{ hostname }}"
      when: hostname is defined

    - name: Enable IPv4 routing
      cisco.ios.ios_config:
        lines:
          - "ip routing"
      when: enable_ip_routing | default(false) | bool

    - name: Enable IPv6 routing
      cisco.ios.ios_config:
        lines:
          - "ipv6 unicast-routing"
      when: enable_ipv6_routing | default(false) | bool

    - name: Configure misc commands with parent sections
      cisco.ios.ios_config:
        parents: "{{ item.parents }}"
        lines: "{{ item.lines }}"
      loop: "{{ misc_config | default([]) }}"
      loop_control:
        label: "{{ item.description | default(item.lines | join(',')) }}"
      when:
        - item.parents is defined

    - name: Configure global misc commands
      cisco.ios.ios_config:
        lines: "{{ item.lines }}"
      loop: "{{ misc_config | default([]) }}"
      loop_control:
        label: "{{ item.description | default(item.lines | join(',')) }}"
      when:
        - item.parents is not defined